language: python
python: 3.6

addons:
  chrome: stable

install: make

#before_install:
#  - pip install poetry

install:
  - pip install -r requirements.txt

script:
  - make lint
  - make pytest
  artifacts:
    paths:
      - reports.html
